### ISSUE TITLE
Dialogue Card Progress Numbers Aren't Accessible 

### ISSUE THREAD

**Issue by AEDesigns** [h5p/h5p-dialogcards#126]
When testing inside of Moodle, my team and I found the progress numbers (shown in the picture below) are a grey color and aren't accessible. We tried changing the color in the css, and with javascript, but no luck so I wanted to raise the issue here and submit a pull request if possible to darken the text so it passes accessibility color contrast ratios. 

![progress_num](https://user-images.githubusercontent.com/43253284/166252364-df40b0f1-d21f-42f9-af9e-525e5d752538.png)

**Comment by otacke** [comment]
Hi @AEDesigns 

The color was changed in https://github.com/h5p/h5p-dialogcards/commit/4a7cec0fb61054888108169180ac2c52b453f311 and now yields a contrast ratio od 4.56. The changes will be available one the H5P core teams releases the update.

**Comment by AEDesigns** [comment]
@otacke awesome ty!

**Comment by AEDesigns** [comment]
@icc appreciate it! lol
