### ISSUE TITLE
Web Accessibility

### ISSUE THREAD

**Issue by mgifford** [h5p/h5p-dialogcards#25]
According to http://facdev.e-education.psu.edu/instdesigner/h5p

This module isn't accessible. Is this still accurate? What efforts have been made to see that this meets WCAG 2.0 AA?

**Comment by timothyylim** [comment]
Hi @mgifford , with the next release Dialog Cards will be accessible to WCAG 2.0 AA standards with good ARIA coverage:

https://h5ptechnology.atlassian.net/browse/HFP-1198
