### ISSUE TITLE
Sound not working on Mode repetition, on second round

### ISSUE THREAD

**Issue by Andmat7** [h5p/h5p-dialogcards#56]
Sound not working on Mode repetition, on second round

**Comment by otacke** [comment]
Hi @Andmat7 
Thanks for reporting. I fixed the problem in https://github.com/h5p/h5p-dialogcards/pull/57 but it still needs to be accepted and released.

**Comment by fnoks** [comment]
Otacke's PR is merged in, and Dialog Cards is released on h5p.org.

@Andmat7  -> Thanks a lot for reporting, and sorry for this taking so long :(

@otacke -> Thanks a lot for fixing this one :+1:

**Comment by otacke** [comment]
@fnoks Just cleaning up my own mess ...
