### ISSUE TITLE
Ability to add a different image on back of card

### ISSUE THREAD

**Issue by supriyarajgopal-spi** [h5p/h5p-dialogcards#8]
I had a requirement of being able to add a different image on the back of the dialog card so that when a user clicks on 'Turn', different image is shown.
I have added this functionality [here](https://github.com/h5p/h5p-dialogcards/pull/7).

Kindly look into and do the needful.

Regards,
Supriya Rajgopal

**Comment by icc** [comment]
Thank you, we will review the code changes very soon!

**Comment by thomasmars** [comment]
This issue is being tracked from PR #11 therefore closing this issue.
